language: android
jdk: oraclejdk7
android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.2
    # The SDK version used to compile your project
    - android-23
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./wait_for_emulator

script: mvn clean install -Pintegration-tests -Dandroid.device=test
